# alembic/script.py.mako
"""Create initial tables

Revision ID: 7776edb3262e
Revises: 
Create Date: 2026-01-07 15:02:24.465071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7776edb3262e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_pk_id'), 'category', ['pk_id'], unique=False)
    op.create_table('training_center',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=True),
    sa.Column('owner', sa.String(length=30), nullable=True),
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_training_center_pk_id'), 'training_center', ['pk_id'], unique=False)
    op.create_table('athlete',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('height', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('training_center_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.pk_id'], ),
    sa.ForeignKeyConstraint(['training_center_id'], ['training_center.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_athlete_pk_id'), 'athlete', ['pk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_pk_id'), table_name='athlete')
    op.drop_table('athlete')
    op.drop_index(op.f('ix_training_center_pk_id'), table_name='training_center')
    op.drop_table('training_center')
    op.drop_index(op.f('ix_category_pk_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###